debugging

diff --git a/.github/workflows/integration-tests.yaml b/.github/workflows/integration-tests.yaml
--- a/.github/workflows/integration-tests.yaml
+++ b/.github/workflows/integration-tests.yaml
@@ -23,37 +23,46 @@ jobs:
         with:
           node-version: '18.17.1'
 
-      - name: Cache dependencies
-        uses: actions/cache@v2
-        with:
-          path: ~/.npm
-          key: npm-${{ hashFiles('package-lock.json') }}
-          restore-keys: npm-
-
-      - name: Install dependencies
-        run: yarn install
-
-      - name: Build
-        run: yarn build
-
-      - name: Lint
-        run: yarn lint
-
-      - name: Integration Tests
+      - name: Echo PR Info
+        run: |
+          echo "PR Number: $PR_NUMBER"
+          echo "PR Title: $PR_TITLE"
         env:
-          CERTS_API_KEY: ${{ secrets.CERTS_API_KEY }}
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-          PR_LINK: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
-          GITHUB_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        run: | 
-          export NODE_OPTIONS="--max_old_space_size=12096"
-          export CI=true
-          yarn test:integration
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+          PR_TITLE: ${{ github.event.pull_request.title }}
+      # - name: Cache dependencies
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: ~/.npm
+      #     key: npm-${{ hashFiles('package-lock.json') }}
+      #     restore-keys: npm-
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure() 
-        with:
-          name: Integration Test Report
-          path: reports/jest-*.xml
-          reporter: jest-junit 
+      # - name: Install dependencies
+      #   run: yarn install
+
+      # - name: Build
+      #   run: yarn build
+
+      # - name: Lint
+      #   run: yarn lint
+
+      # - name: Integration Tests
+      #   env:
+      #     CERTS_API_KEY: ${{ secrets.CERTS_API_KEY }}
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      #     PR_LINK: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}
+      #     PR_NUMBER: ${{ github.event.pull_request.number }}
+      #     PR_TITLE: ${{ github.event.pull_request.title }}
+      #     GITHUB_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      #   run: | 
+      #     export NODE_OPTIONS="--max_old_space_size=12096"
+      #     export CI=true
+      #     yarn test:integration
+
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure() 
+      #   with:
+      #     name: Integration Test Report
+      #     path: reports/jest-*.xml
+      #     reporter: jest-junit 
