debugging

diff --git a/.github/workflows/integration-tests.yaml b/.github/workflows/integration-tests.yaml
--- a/.github/workflows/integration-tests.yaml
+++ b/.github/workflows/integration-tests.yaml
@@ -23,6 +23,11 @@ jobs:
         with:
           node-version: '18.17.1'
 
+      - name: Install GitHub CLI
+        run: |
+          sudo apt update
+          sudo apt install -y gh
+
       - name: Echo PR Info
         run: |
           echo "PR Number: $PR_NUMBER"
@@ -32,6 +37,17 @@ jobs:
           PR_NUMBER: ${{ github.event.pull_request.number }}
           PR_TITLE: ${{ github.event.pull_request.title }}
           BRANCH: ${{ github.ref_name}}
+
+      - name: Fetch Open PR for Branch
+        env:
+          BRANCH: ${{ github.ref_name }}
+        run: |
+          PR=$(gh pr list --base $BRANCH --state open --json number,title -q ".[0]")
+          PR_NUMBER=$(echo $PR | jq -r ".number")
+          PR_TITLE=$(echo $PR | jq -r ".title")
+          echo "PR Number: $PR_NUMBER"
+          echo "PR Title: $PR_TITLE"
+          echo "Branch: $BRANCH"
 
       - name: Debug GitHub Context
         env:
@@ -61,15 +77,15 @@ jobs:
       #     PR_NUMBER: ${{ github.event.pull_request.number }}
       #     PR_TITLE: ${{ github.event.pull_request.title }}
       #     GITHUB_ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-      #   run: | 
+      #   run: |
       #     export NODE_OPTIONS="--max_old_space_size=12096"
       #     export CI=true
       #     yarn test:integration
 
       # - name: Test Report
       #   uses: dorny/test-reporter@v1
-      #   if: success() || failure() 
+      #   if: success() || failure()
       #   with:
       #     name: Integration Test Report
       #     path: reports/jest-*.xml
-      #     reporter: jest-junit 
+      #     reporter: jest-junit
